### ISSUE TITLE
Windows platform support

### ISSUE THREAD

**Issue by BFergerson** [bblfsh/scala-client#102]
It looks like the current scala-client doesn't properly handle Windows. The same code works on Ubuntu 18.04 but causes an NPE at https://github.com/bblfsh/scala-client/blob/master/src/main/scala/org/bblfsh/client/v2/libuast/Libuast.scala#L62 on Windows.

It seems this is due to the scala-client not embedding the `libuast.dll` and loading this instead of `libscalauast.so`. Is this correct? If so, shouldn't the effort to get scala-client working with Windows be fairly low? I'm only seeing small changes to `Libuast.scala` and `build.sbt` being necessary. Am I missing something?

**Comment by bzz** [comment]
Thank you for this feature request!

Adding win platform support should not be very hard, given that [libuast releases](https://github.com/bblfsh/libuast/releases) do ship windows binary.

I'm not very familiar with windows toolchain so it most probably will take some time to add it. 
For *nix we link `libscalauast` with libuast statically to get a single binary.

After figuring that part out, we also will need either a separate CI profile for Win release using AppVeyor + update the TravisCI release to fetch Win library, or somehow cross-compile from linux using mingwin.

**Comment by bzz** [comment]
So the action items will be:

 - [ ] add new CI release profile on AppVeyor for Win build of `libscalauast.dll` (linked statically with `libuast.lib`) that publishes binary to GH release
 - [ ] update CI release profile on Travis to include Win native artifacts
 - [ ] support for loading `.dll` in `Libuast.scala`

**Comment by ncordon** [comment]
Done, but using Windows Travis support! Watiting #134 to be finished and reviewed. Stay tuned!

**Comment by ncordon** [comment]
@BFergerson, new release of `scala-client` [2.0.1](https://github.com/bblfsh/scala-client/releases/tag/v2.1.0) adds support for Windows
