### ISSUE TITLE
v2: expose output UAST encoding options

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#107]
libuast provides multiple encoding options: binary, yaml, JSON.

Right now we have a [binary on by default in ContextExt](https://github.com/bblfsh/scala-client/blob/fabffddbbc673a34b16637c88da5f8d660d71b22/src/main/native/org_bblfsh_client_v2_libuast_Libuast.cc#L584) and [Context.encode()](https://github.com/bblfsh/scala-client/blob/fabffddbbc673a34b16637c88da5f8d660d71b22/src/main/native/org_bblfsh_client_v2_libuast_Libuast.cc#L551), and this issue is about exposing other options though API surface, keeping binary a default.

**Comment by ncordon** [comment]
This is just to double check in case I am missing something: `libuast` does not seem to support JSON currently: https://github.com/bblfsh/libuast/blob/1fd3a507f3a6d327824274c003cdcede2b07c0fa/src/uast.h#L106

Should it?

**Comment by kuba--** [comment]
in python client 0 is binary, 1 is yaml, so it's consistent. 
It's not a problem to add another one, but I don't think any client supports it, so far.

**Comment by ncordon** [comment]
Thanks @kuba-- : )
