### ISSUE TITLE
v2: expose new iteration orders

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#108]
libuast provides multiple node iteration options: [pre, post, children, position, etc](https://github.com/bblfsh/libuast/blob/b69f7e5f7337db563e96f04dbcf91d6eb61271ef/src/uast.h#L64)

Right now we have a [4 orders exposed](https://github.com/bblfsh/scala-client/blob/fabffddbbc673a34b16637c88da5f8d660d71b22/src/main/scala/org/bblfsh/client/v2/BblfshClient.scala#L104) and this issue is about: 
 - bumping libuast version to the latest
 - making sure all the orders are exposed in JVM
 - adding more tests, covering other iterations orders [besides PreOrder](https://github.com/bblfsh/scala-client/blob/209838003bd42682178e1889dea7bfed44c8afb7/src/test/scala/org/bblfsh/client/v2/LibuastManagedIteratorTest.scala#L74)

**Comment by ncordon** [comment]
I am noticing I did not add more test coverage, so I would increase it in the PR I am preparing and close this.
