### ISSUE TITLE
v2: add a cache to JNI part

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#114]
On the JNI side, we can cache a lot of things as global references instead of calling JVM every time:
 - classes, instead of `env->FindClass`
 - methodIds, instead of `env->GetMethodID` for things in hot `checkJvmException`

This can be done in `JNI_OnLoad` and all global reference must be deleted e.g in `JNI_OnUnLoad`.

**Comment by creachadair** [comment]
This seems like a very reasonable idea. I would like to consider this a low-priority feature request, however, until we have some evidence that it is necessary—meaning that the performance as-written is not sufficient for existing use, and that we can concretely measure how much improvement a cache gives us to verify we met the need.
