### ISSUE TITLE
Publish latest release on Maven

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#123]
Right now latest release [v2.0.1]() has failed on publishing to Maven (https://github.com/src-d/infrastructure/issues/1125).

The idea is, in order to unblock https://github.com/src-d/gitbase-spark-connector-enterprise/pull/93 to release a `v2.0.2-SNAPSHOT`.

The last attempt of releasing from master though has failed on macOS cross-compilation

TODOs:
 - [x] add new CI profile for macOS cross-compilation to `.travis.yml`
    In order to reproduce a failure from v2.0.2 release
   ```
    - <<: *release
      stage: test
      script: ./sbt assembly test
   ```
 - [x] fix macOS build that seems to be failing on STDLIB usage
    [Build logs](https://travis-ci.org/bblfsh/scala-client/jobs/577311092)
   ```
   
   In file included from src/main/native/org_bblfsh_client_v2_libuast_Libuast.cc:14:
   In file included from src/main/resources/libuast/libuast.hpp:6:
   In file included from /home/travis/osxcross/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/unordered_map:350:
   /home/travis/osxcross/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:1163:43: error: exception specification in declaration does not match previous declaration
   __hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table()
                                             ^
   /home/travis/osxcross/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:850:5: note: previous declaration is here
       __hash_table()
       ^
   /home/travis/osxcross/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:1231:43: error: exception specification in declaration does not match previous declaration
   __hash_table<_Tp, _Hash, _Equal, _Alloc>::__hash_table(__hash_table&& __u)
                                             ^
   /home/travis/osxcross/bin/../SDK/MacOSX10.11.sdk/usr/include/c++/v1/__hash_table:864:5: note: previous declaration is here
       __hash_table(__hash_table&& __u)
       ^
   2 errors generated.
   ```
 - [x] release a `v2.0.2-SNAPSHOT` and make sure [it's published](https://oss.sonatype.org/content/repositories/snapshots/org/bblfsh/bblfsh-client/)

**Comment by ncordon** [comment]
Blocked by https://github.com/src-d/infrastructure/issues/1125
Blocking https://github.com/src-d/gitbase-spark-connector-enterprise/pull/93

**Comment by ncordon** [comment]
Version [v2.0.2](https://github.com/bblfsh/scala-client/releases/tag/v2.0.2) has been published (instead of the SNAPSHOT one)
