### ISSUE TITLE
Why JUInts?

### ISSUE THREAD

**Issue by ncordon** [bblfsh/scala-client#127]
Is there any strong reason to use [`JUints`](https://github.com/bblfsh/scala-client/blob/c4c15bbf848d17538f42ea09b370b1ece32795f8/src/main/scala/org/bblfsh/client/v2/NodeExt.scala#L153) when Scala does not support the `Unsigned Int` type and [`python-client`](https://github.com/bblfsh/python-client/blob/f4ddc558d49f5fb3e93f73b88d98548adc40ebce/bblfsh/pyuast.cc#L455) does not support them either?

Well, in fact in the `python-client` we have [ways of casting](https://github.com/bblfsh/python-client/blob/f4ddc558d49f5fb3e93f73b88d98548adc40ebce/bblfsh/pyuast.cc#L517) to `uint64` in the native part, but they are never going to get called, since the type of node, as linked before, is not going to ever return `NODE_UINT`

**Comment by bzz** [comment]
Good point. Honestly, I do not think we really need it. 

It was just added as an attempt to implement the interface that we have on the native side with the conversion in the managed code.

I think it's safe to drop it and document that behavior is similar to python-client.

**Comment by ncordon** [comment]
This can be closed, since having `JUint`s seems to be protecting against losing bytes in `encoding ∘decoding` operations. The same cannot be said about the `python-client`, so will open an issue there.
