### ISSUE TITLE
Investigate released artifact size increase

### ISSUE THREAD

**Issue by bzz** [bblfsh/scala-client#85]
Investigate and document JAR file increase -  v1.11.0 jar [published on Maven](https://oss.sonatype.org/#nexus-search;quick~bblfsh) is 1.31 MB while `bblfsh-client-2.0.0-SNAPSHOT.jar` from #83 is 8.0 MB.

**Comment by dennwc** [comment]
If it's from the new `libuast` v3 build, then it's the statically linked Go runtime adding those ~6 MB :)

**Comment by bzz** [comment]
That was my guess, but leaving an issue for a proper research.
E.g there is an option to strip debug symbols, etc
